<?php

namespace Database\Seeders;

use App\Models\Indicator;
use App\Models\StandardStatement;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\File as FacadesFile;


class StandardStatementSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        //
        $data = [
    ["id" => "1", "name" => "Wakil Rektor I memastikan setiap program studi memiliki standar kompetensi lulusan yang mencakup sikap, pengetahuan, dan keterampilan yang dinyatakan dalam capaian pembelajaran lulusan", "standard_criteria_id" => "1"],
    ["id" => "2", "name" => "Universitas memiliki kebijakan pengembangan kurikulum yang mempertimbangkan keterkaitan dengan visi dan misi (mandat) perguruan tinggi, pengembangan ilmu pengetahuan dan kebutuhan stakeholders", "standard_criteria_id" => "1"],
    ["id" => "3", "name" => "Program Studi memastikan luaran tugas akhir mahasiswa sesuai standar minimal yang ditetapkan", "standard_criteria_id" => "1"],
    ["id" => "4", "name" => "Program studi memastikan rumusan pengetahuan dan keterampilan khusus sebagai bagian dari capaian pembelajaran lulusan wajib disusun oleh forum program studi sejenis, atau pengelola program studi dalam hal tidak memiliki forum program studi sejenis.", "standard_criteria_id" => "1"],
    ["id" => "5", "name" => "Program Studi melakukan analisis pemenuhan capaian pembelajaran lulusan yang dilakukan menggunakan metode pembelajaran yang sahih dan relevan", "standard_criteria_id" => "1"],
    ["id" => "6", "name" => "Program Studi melakukan pengukuran terhadap capaian pembelajaran lulusan", "standard_criteria_id" => "1"],
    ["id" => "7", "name" => "Universitas memiliki kebijakan pengembangan kurikulum yang mempertimbangkan keterkaitan dengan visi dan misi (mandat) perguruan tinggi, pengembangan ilmu pengetahuan dan kebutuhan stakeholders", "standard_criteria_id" => "2"],
    ["id" => "8", "name" => "Universitas memiliki pedoman pengembangan kurikulum", "standard_criteria_id" => "2"],
    ["id" => "9", "name" => "Universitas memiliki pedoman pelaksanaan kurikulum yang mencakup pemantauan dan peninjauan kurikulum yang mempertimbangkan umpan balik dari para pemangku kepentingan, pencapaian isu-isu strategis untuk menjamin kesesuaian dan kemutakhirannya.", "standard_criteria_id" => "2"],
    ["id" => "10", "name" => "Program Studi melakukan evaluasi dan pemutakhiran kurikulum secara berkala dan melibatkan pemangku kepentingan", "standard_criteria_id" => "2"],
    ["id" => "11", "name" => "Program Studi memastikan kedalaman dan keluasan materi pembelajaran dirumuskan dengan mengacu pada capaian pembelajaran lulusan dan deskripsi capaian pembelajaran lulusan dari KKNI", "standard_criteria_id" => "2"],
    ["id" => "12", "name" => "Program Studi memastikan tingkat kedalaman dan keluasan materi pembelajaran bersifat kumulatif dan/atau integratif", "standard_criteria_id" => "2"],
    ["id" => "13", "name" => "Program Studi memastikan tingkat kedalaman dan keluasan materi pembelajaran dituangkan dalam bahan kajian yang distrukturkan dalam bentuk mata kuliah.", "standard_criteria_id" => "2"],
    ["id" => "14", "name" => "Universitas harus memiliki pedoman pelaksanaan proses pembelajaran yang mencakup perencanaan, pelaksanaan, dan evaluasi", "standard_criteria_id" => "3"],
    ["id" => "15", "name" => "Universitas memiliki dokumen formal kebijakan dan pedoman untuk mengintegrasikan kegiatan penelitian dan PkM ke dalam pembelajaran", "standard_criteria_id" => "3"],
    ["id" => "16", "name" => "Program Studi memastikan karakteristik proses pembelajaran mencakup sifat interaktif, holistik, integratif, saintifik, kontekstual, tematik, efektif, kolaboratif, dan berpusat pada mahasiswa", "standard_criteria_id" => "3"],
    ["id" => "17", "name" => "Program Studi harus memastikan setiap mata kuliah dilengkapi dengan Rencana Pembelajaran Semester (RPS) yang ditetapkan dan dikembangkan oleh dosen secara mandiri atau bersama dalam kelompok keahlian", "standard_criteria_id" => "3"],
    ["id" => "18", "name" => "Program Studi memastikan Rencana pembelajaran semester (RPS) harus memuat informasi yang lengkap mengenai mata kuliah", "standard_criteria_id" => "3"],
    ["id" => "19", "name" => "Program Studi memastikan Rencana Pembelajaran Semester (RPS) ditinjau secara berkala dan disesuaikan dengan perkembangan ilmu pengetahuan dan teknologi", "standard_criteria_id" => "3"],
    ["id" => "20", "name" => "Dosen harus melaksanakan perkuliahan sesuai dengan Rencana Pembelajaran Semester (RPS)", "standard_criteria_id" => "3"],
    ["id" => "21", "name" => "Universitas memiliki dokumen formal kebijakan suasana akademik yang mencakup: otonomi keilmuan, kebebasan akademik, dan kebebasan mimbar akademik", "standard_criteria_id" => "3"],
    ["id" => "22", "name" => "Wakil Rektor I melakukan pengukuran tentang terbangunnya suasana akademik yang kondusif yang dapat berupa: a) Keterlaksanaan interaksi akademik antar sivitas akademika dalam kegiatan pendidikan, penelitian dan PkM b) Keterlaksanaan program/kegiatan non akademik yang melibatkan seluruh warga kampus yang didukung oleh ketersediaan sarana, prasarana, dan dana yang memadai.", "standard_criteria_id" => "3"],
    ["id" => "23", "name" => "Universitas melakukan langkah-langkah strategis untuk meningkatkan suasana akademik.", "standard_criteria_id" => "3"],
    ["id" => "24", "name" => "Program Studi memastikam pelaksanaan proses pembelajaran berlangsung dalam bentuk interaksi antara dosen, mahasiswa, dan sumber belajar dalam lingkungan belajar tertentu", "standard_criteria_id" => "3"],
    ["id" => "25", "name" => "Program Studi harus memastikan bentuk pembelajaran dapat berupa: a. kuliah; b. responsi dan tutorial; c. seminar; d. praktikum, praktik studio, praktik bengkel, praktik lapangan, praktik kerja; e. penelitian, perancangan, atau pengembangan; f. pelatihan militer; g. pertukaran pelajar; h. magang; i. wirausaha; dan/atau j. bentuk lain pengabdian kepada masyarakat.", "standard_criteria_id" => "3"],
    ["id" => "26", "name" => "Universitas wajib memfasilitasi pelaksanaan bentuk pembelajaran berupa: a. kuliah; b. responsi dan tutorial; c. seminar; d. praktikum, praktik studio, praktik bengkel, praktik lapangan, praktik kerja; e. penelitian, perancangan, atau pengembangan; f. pelatihan militer; g. pertukaran pelajar; h. magang; i. wirausaha; dan/atau j. bentuk lain pengabdian kepada masyarakat di dalam Prodi dan di luar Prodi (Transfer Kredit)", "standard_criteria_id" => "3"],
    ["id" => "27", "name" => "Universitas memastikan masa studi dan beban belajar mahasiswa sesuai SN-Dikti", "standard_criteria_id" => "3"],
    ["id" => "28", "name" => "Wakil Rektor I melakukan monitoring dan evaluasi terhadap proses pelaksanaan perkuliahan", "standard_criteria_id" => "3"],
    ["id" => "29", "name" => "Wakil Rektor I melakukan survey kepuasan mahasiswa terhadap proses pembelajaran", "standard_criteria_id" => "3"],
    ["id" => "30", "name" => "Program Studi melakukan evaluasi terhadap prestasi akademik mahasiswa di setiap semester", "standard_criteria_id" => "3"],
    ["id" => "31", "name" => "Universitas memiliki pedoman penilaian proses dan hasil pembelajaran mahasiswa untuk pemenuhan capaian pembelajaran lulusan.", "standard_criteria_id" => "4"],
    ["id" => "32", "name" => "Dosen harus melaksanakan prinsip penilaian mencakup prinsip edukatif, otentik, objektif, akuntabel, dan transparan yang dilakukan secara terintegrasi", "standard_criteria_id" => "4"],
    ["id" => "33", "name" => "Dosen harus melaksanakan penilaian menggunakan teknik penilaian berupa observasi, partisipasi, unjuk kerja, tes tertulis, tes lisan, dan angket sesuai dengan capaian pembelajaran lulusan", "standard_criteria_id" => "4"],
    ["id" => "34", "name" => "Dosen harus melaksnanakan penilaian menggunakan instrumen penilaian proses dalam bentuk rubrik, dan/atau penilaian hasil dalam bentuk fortopolio atau karya desain sesuai dengan capaian pembelajaran lulusan", "standard_criteria_id" => "4"],
    ["id" => "35", "name" => "Dosen harus memiliki kontrak rencana penilaian (tahap, teknik, instrumen, kriteria, indikator, dan bobot penilaian)", "standard_criteria_id" => "4"],
    ["id" => "36", "name" => "Dosen melaksanakan penilaian sesuai kontrak atau kesepakatan yang disampaikan di awal perkuliahan", "standard_criteria_id" => "4"],
    ["id" => "37", "name" => "Dosen harus memberikan umpan balik dan kesempatan untuk mempertanyakan hasil penilaian kepada mahasiswa", "standard_criteria_id" => "4"],
    ["id" => "38", "name" => "Dosen harus mendokumentasikan penilaian proses dan hasil belajar mahasiswa secara akuntabel dan transparan", "standard_criteria_id" => "4"],
    ["id" => "39", "name" => "Dosen memiliki prosedur penilaian mencakup tahap perencanaan, kegiatan pemberian tugas atau soal, observasi kinerja, pengembalian hasil observasi, dan pemberian nilai akhir", "standard_criteria_id" => "4"],
    ["id" => "40", "name" => "Dosen harus melaporkan hasil penilaian berupa kualifikasi keberhasilan mahasiswa dalam menempuh suatu mata kuliah dalam bentuk huruf dan angka", "standard_criteria_id" => "4"],
    ["id" => "41", "name" => "Dosen melakukan proses perbaikan terhadap hasil monev penilaian", "standard_criteria_id" => "4"],
    ["id" => "42", "name" => "Universitas mengumumkan hasil penilaian capaian pembelajaran lulusan di tiap semester yang dinyatakan dengan indeks prestasi semester (IPS)", "standard_criteria_id" => "4"],
    ["id" => "43", "name" => "BAAK mengumumkan Hasil penilaian capaian pembelajaran lulusan pada akhir program studi yang dinyatakan dengan indeks prestasi kumulatif (IPK)", "standard_criteria_id" => "4"],
    ["id" => "44", "name" => "Mahasiswa program sarjana dinyatakan lulus apabila telah menempuh seluruh beban belajar yang ditetapkan dan memiliki capaian pembelajaran lulusan yang ditargetkan oleh program studi dengan indeks prestasi kumulatif (IPK) lebih besar atau sama dengan 2,00", "standard_criteria_id" => "4"],
    ["id" => "45", "name" => "Universitas wajib memberikan ijazah, sertifikat profesi, gelar, dan surat keterangan pendamping ijazah, bagi mahasiswa yang dinyatakan lulus", "standard_criteria_id" => "4"],
    ["id" => "46", "name" => "Universitas memiliki kualifikasi akademik dan kompetensi dosen, sehat jasmani dan rohani, serta memiliki kemampuan untuk menyelenggarakan pendidikan dalam rangka pemenuhan capaian pembelajaran lulusan", "standard_criteria_id" => "5"],
    ["id" => "47", "name" => "Wakil Rektor I memastikan jumlah dosen pada setiap program studi harus mendukung proses pembelajaran yang bermutu.", "standard_criteria_id" => "5"],
    ["id" => "48", "name" => "Universitas memiliki pedoman perhitungan beban kerja dosen yang mencakup kegiatan tugas pokok, kegiatan tugas tambahan, dan kegiatan penunjang", "standard_criteria_id" => "5"],
    ["id" => "49", "name" => "Wakil Rektor II menjamin beban kinerja dosen mengacu pada rasio dosen dan mahasiswa", "standard_criteria_id" => "5"],
    ["id" => "50", "name" => "Wakil Rektor II melakukan upaya pengembangan Dosen Tetap Program Studi (DTPS) sesuai Renstra Universitas secara konsisten", "standard_criteria_id" => "5"],
    ["id" => "51", "name" => "Universitas memiliki tenaga kependidikan yang memenuhi tingkat kecukupan dan kualifikasi berdasarkan jenis pekerjaannya (pustakawan, laboran, teknisi, dll.) untuk mendukung pelaksanaan tridharma, fungsi dan pengembangan institusi secara efektif", "standard_criteria_id" => "5"],
    ["id" => "52", "name" => "Universitas melakukan upaya pengembangan Tenaga Kependidikan", "standard_criteria_id" => "5"],
    ["id" => "53", "name" => "Universitas memastikan ketersediaan sarana pembelajaran sesuai isi dan proses pembelajaran serta memenuhi persyaratan sebagai sarana pembelajaran yang berkualitas, paling sedikit meliputi a. perabot; b. peralatan pendidikan; c. media pendidikan; d. buku, buku elektronik, dan repositori; e. sarana teknologi informasi dan komunikasi; f. instrumentasi eksperimen; g. sarana olahraga; h. sarana berkesenian; i. sarana fasilitas umum; j. bahan habis pakai; dan k. sarana pemeliharaan, keselamatan, dan keamanan.", "standard_criteria_id" => "6"],
    ["id" => "54", "name" => "Universitas harus menjamin tersedianya prasarana pembelajaran sesuai isi dan proses pembelajaran serta memenuhi persyaratan sebagai prasarana pembelajaran yang berkualitas, paling sedikit meliputi : a. lahan; b. ruang kelas; c. perpustakaan; d. laboratorium/studio/bengkel kerja/unit produksi; e. tempat berolahraga; f. ruang untuk berkesenian; g. ruang unit kegiatan mahasiswa; h. ruang pimpinan perguruan tinggi; i. ruang dosen; j. ruang tata usaha; dan k. fasilitas umum.", "standard_criteria_id" => "6"],
    ["id" => "55", "name" => "\"Universitas harus memastikan tersedianya sarana dan prasarana yang dapat diakses oleh mahasiswa yang berkebutuhan khusus\"", "standard_criteria_id" => "6"],
    ["id" => "56", "name" => "Universitas memastikan pelaksana standar pengelolaan pembelajaran dilakukan oleh Wakil Rektor I sebagai Unit Pengelola program Studi", "standard_criteria_id" => "7"],
    ["id" => "57", "name" => "Program Studi wajib melakukan penyusunan kurikulum dan rencana pembelajaran dalam setiap mata kuliah", "standard_criteria_id" => "7"],
    ["id" => "58", "name" => "Program studi wajib menyelenggarakan program pembelajaran sesuai standar isi, standar proses, standar penilaian yang telah ditetapkan dalam rangka mencapai capaian pembelajaran lulusan", "standard_criteria_id" => "7"],
    ["id" => "59", "name" => "Program studi wajib melakukan kegiatan sistemik yang menciptakan suasana akademik dan budaya mutu yang baik", "standard_criteria_id" => "7"],
    ["id" => "60", "name" => "Program studi wajib melakukan kegiatan pemantauan dan evaluasi secara periodik dalam rangka menjaga dan meningkatkan mutu proses pembelajaran", "standard_criteria_id" => "7"],
    ["id" => "61", "name" => "Program studi wajib melaporkan hasil program pembelajaran secara periodik sebagai sumber data dan informasi dalam pengambilan keputusan perbaikan dan pengembangan mutu pembelajaran","standard_criteria_id" => "7"],
    ["id" => "62", "name" => "Universitas wajib menyusun kebijakan, rencana strategis, dan operasional terkait dengan pembelajaran yang dapat diakses oleh sivitas akademika dan pemangku kepentingan, serta dapat dijadikan pedoman bagi program studi dalam melaksanakan program pembelajaran","standard_criteria_id" => "7"],
    ["id" => "63", "name" => "Universitas harus menyelenggarakan pembelajaran sesuai dengan jenis dan program pendidikan yang selaras dengan capaian pembelajaran lulusan","standard_criteria_id" => "7"],
    ["id" => "64", "name" => "Universitas wajib menjaga dan meningkatkan mutu pengelolaan program studi dalam melaksanakan program pembelajaran secara berkelanjutan dengan sasaran yang sesuai dengan visi dan misi perguruan tinggi","standard_criteria_id" => "7"],
    ["id" => "65", "name" => "Universitas wajib melakukan pemantauan dan evaluasi terhadap kegiatan program studi dalam melaksanakan kegiatan pembelajaran","standard_criteria_id" => "7"],
    ["id" => "66", "name" => "Universitas wajib memiliki panduan perencanaan, pelaksanaan, evaluasi, pengawasan, penjaminan mutu, dan pengembangan kegiatan pembelajaran dan dosen","standard_criteria_id" => "7"],
    ["id" => "67", "name" => "Universitas wajib menyampaikan laporan kinerja program studi dalam menyelenggarakan program pembelajaran paling sedikit melalui pangkalan data pendidikan tinggi","standard_criteria_id" => "7"],
    ["id" => "68", "name" => "Universitas memiliki standar satuan biaya operasional yang digunakan sebagai dasar untuk menyusun rencana anggaran pendapatan dan belanja (RAPB) tahunan dan penetapan biaya yang ditanggung oleh mahasiswa","standard_criteria_id" => "8"],
    ["id" => "69", "name" => "Universitas wajib mempunyai sistem pencatatan biaya dan melaksanakan pencatatan biaya sesuai dengan ketentuan peraturan perundang-undangan sampai pada satuan program studi","standard_criteria_id" => "8"],
    ["id" => "70", "name" => "Universitas harus melakukan analisis biaya operasional pendidikan tinggi sebagai bagian dari penyusunan rencana kerja dan anggaran tahunan perguruan tinggi","standard_criteria_id" => "8"],
    ["id" => "71", "name" => "Universitas harus melakukan evaluasi tingkat ketercapaian standar satuan biaya pendidikan tinggi pada setiap akhir tahun anggaran","standard_criteria_id" => "8"],
    ["id" => "72", "name" => "Yayasan/Universitas wajib mengupayakan pendanaan pendidikan tinggi dari berbagai sumber di luar biaya pendidikan yang diperoleh dari mahasiswa","standard_criteria_id" => "8"],
    ["id" => "73", "name" => "Universitas wajib menyusun kebijakan, mekanisme, dan prosedur dalam menggalang sumber dana lain secara akuntabel dan transparan dalam rangka peningkatan kualitas pendidikan","standard_criteria_id" => "8"],
    ["id" => "74", "name" => "Lembaga Penelitian mendorong hasil penelitian dosen dan mahasiswa diarahkan dalam rangka pengembangan ilmu pengetahuan dan teknologi yang mengacu pada visi-misi serta dapat meningkatkan kesejahteraan masyarakat dan daya saing bangsa","standard_criteria_id" => "9"],
    ["id" => "75", "name" => "Lembaga Penelitian memastikan hasil penelitian dosen dan mahasiswa memenuhi kaidah dan metode ilmiah secara sistematis sesuai otonomi keilmuan dan budaya akademik.","standard_criteria_id" => "9"],
    ["id" => "76", "name" => "Program Studi memastikan hasil penelitian mahasiswa (tugas akhir/skripsi dan sejenisnya) harus memenuhi capaian pembelajaran lulusan","standard_criteria_id" => "9"],
    ["id" => "77", "name" => "Lembaga Penelitian mewajibkan semua hasil penelitian dosen dipublikasikan di tingkat nasional dan Internasional","standard_criteria_id" => "9"],
    ["id" => "78", "name" => "Lembaga Penelitian memastikan artikel karya ilmiah dosen memberi impact pada perkembangan ilmu pengetahuan","standard_criteria_id" => "9"],
    ["id" => "79", "name" => "Lembaga Penelitian memastikan hilirisasi hasil penelitian dilaksanakan","standard_criteria_id" => "9"],
    ["id" => "80", "name" => "Lembaga penelitian memfasilitasi kegiatan diseminasi hasil penelitian dosen","standard_criteria_id" => "9"],
    ["id" => "81", "name" => "Lembaga penelitian mendorong hasil penelitian dosen di program sarjana dan magister digunakan sebagai rujukan tema skripsi/tesis mahasiswa", "standard_criteria_id" => "9"],
    ["id" => "82", "name" => "Lembaga penelitian memastikan kualitas dan relevansi tujuan, permasalahan, state of the art, metode, dan kebaruan penelitian sangat signifikan.", "standard_criteria_id" => "10"],
    ["id" => "83", "name" => "Lembaga penelitian memastikan tingkat kedalaman dan keluasan materi pada penelitian dasar berorientasi pada luaran penelitian yang berupa penjelasan atau penemuan untuk mengantisipasi suatu gejala, fenomena, kaidah, model, atau postulat baru.", "standard_criteria_id" => "10"],
    ["id" => "84", "name" => "Lembaga penelitian memastikan tingkat kedalaman dan keluasan materi pada penelitian terapan harus berorientasi pada luaran penelitian yang berupa inovasi serta pengembangan ilmu pengetahuan dan teknologi yang bermanfaat bagi masyarakat, dunia usaha, dan/atau industri dan mengantisipasi kebutuhan masa mendatang.", "standard_criteria_id" => "10"],
    ["id" => "85", "name" => "Lembaga penelitian memastikan materi pada penelitian dasar dan penelitian terapan harus memuat prinsip-prinsip kemanfaatan, kemutakhiran, dan mengantisipasi kebutuhan masa mendatang.", "standard_criteria_id" => "10"],
    ["id" => "86", "name" => "Lembaga penelitian memiliki dokumen formal Rencana Strategis Penelitian yang memuat landasan pengembangan, peta jalan penelitian, sumber daya, sasaran program strategis dan indikator kinerja.", "standard_criteria_id" => "11"],
    ["id" => "87", "name" => "Lembaga penelitian memiliki pedoman penelitian yang mencakup perencanaan, pelaksanaan, dan pelaporan kegiatan", "standard_criteria_id" => "11"],
    ["id" => "88", "name" => "Program studi memiliki peta jalan penelitian yang mengacu pada peta jalan penelitian di dalam Renstra Penelitian Universitas", "standard_criteria_id" => "11"],
    ["id" => "89", "name" => "Program studi memiliki peta jalan penelitian yang mengacu pada peta jalan penelitian di dalam Renstra Penelitian Universitas", "standard_criteria_id" => "11"],
    ["id" => "90", "name" => "Dosen yang akan melakukan penelitian harus mengajukan proposal penelitian sesuai dengan pedoman yang telah ditetapkan dan peta jalan penelitian program studi", "standard_criteria_id" => "11"],
    ["id" => "91", "name" => "Lembaga penelitian menunjuk reviewer untuk melakukan proses penilaian terhadap pengajuan penelitian dosen", "standard_criteria_id" => "11"],
    ["id" => "92", "name" => "Lembaga penelitian mengumumkan usulan penelitian yang diterima", "standard_criteria_id" => "11"],
    ["id" => "93", "name" => "Mahasiswa yang akan melakukan penelitian harus mengajukan proposal penelitian sesuai dengan peta jalan penelitian", "standard_criteria_id" => "11"],
    ["id" => "94", "name" => "Program Studi menunjuk reviewer untuk melakukan penilaian terhadap pengajuan penelitian mahasiswa", "standard_criteria_id" => "11"],
    ["id" => "95", "name" => "Dosen harus melaksanakan penelitian sesuai pedoman penelitian yang ditetapkan", "standard_criteria_id" => "11"],
    ["id" => "96", "name" => "Lembaga penelitian memastikan kegiatan penelitian dosen mempertimbangkan standar mutu, keselamatan kerja, kesehatan, kenyamanan, serta keamanan peneliti, masyarakat, dan lingkungan.", "standard_criteria_id" => "11"],
    ["id" => "97", "name" => "Program Studi memastikan kegiatan penelitian mahasiswa dalam rangka melaksanakan tugas akhir/skripsi/tesis mempertimbangkan standar mutu, keselamatan kerja, kesehatan, kenyamanan, serta keamanan peneliti, masyarakat, dan lingkungan.", "standard_criteria_id" => "11"],
    ["id" => "98", "name" => "Program Studi memastikan penelitian mahasiswa dalam rangka melaksanakan tugas akhir/skripsi/tesis sesuai dengan Capaian Pembelajaran lulusan", "standard_criteria_id" => "11"],
    ["id" => "99", "name" => "Program Studi memastikan penelitian yang dilakukan mahasiswa dalam rangka melaksanakan tugas akhir/skripsi/tesis dinyatakan dalam besaran sks", "standard_criteria_id" => "11"],
    [ "id" => "100", "name" => "Dosen dan/atau mahasiswa wajib membuat laporan kemajuan penelitian yang berisi pencapaian penelitian sementara sesuai dengan pedoman yang telah ditetapkan disampaikan Lembaga Penelitian", "standard_criteria_id" => "11" ],
    [ "id" => "101", "name" => "Lembaga Penelitian harus melakukan pemantauan kegiatan penelitian melalui laporan kemajuan penelitian yang dilakukan oleh dosen", "standard_criteria_id" => "11" ],
    [ "id" => "102", "name" => "Dosen dan/atau mahasiswa wajib membuat laporan akhir penelitian yang berisi capaian akhir penelitian sesuai dengan pedoman yang telah ditetapkan kepada Lembaga Penelitian", "standard_criteria_id" => "11" ],
    [ "id" => "103", "name" => "Lembaga penelitian harus melakukan penilaian atas pencapaian penelitian yang dilakukan peneliti", "standard_criteria_id" => "11" ],
    [ "id" => "104", "name" => "Lembaga penelitian memastikan penilaian proses dan hasil penelitian dilakukan secara terintegrasi dengan prinsip penilaian edukatif, objektif, akuntabel dan transparan", "standard_criteria_id" => "12" ],
    [ "id" => "105", "name" => "Lembaga penelitian memastikan penilaian proses dan penelitian memperhatikan kesesuaian dengan standar hasil, standar isi, dan standar proses penelitian.", "standard_criteria_id" => "12" ],
    [ "id" => "106", "name" => "Lembaga penelitian memastikan Penilaian penelitian dapat dilakukan dengan menggunakan metode dan instrumen yang relevan, akuntabel, dan dapat mewakili ukuran ketercapaian kinerja proses serta pencapaian kinerja hasil penelitian", "standard_criteria_id" => "12" ],
    [ "id" => "107", "name" => "Program studi memastikan proses penilaian hasil penelitian yang dilaksanakan oleh mahasiswa untuk penyusunan laporan tugas akhir/skripsi/Tesis telah memenuhi kaidah penelitian sesuai ketentuan dan peraturan yang berlaku", "standard_criteria_id" => "12" ],
    [ "id" => "108", "name" => "Lembaga penelitian memastikan Peneliti wajib memiliki kemampuan tingkat penguasaan metodologi penelitian yang sesuai dengan bidang keilmuan, objek penelitian, serta tingkat kerumitan dan tingkat kedalaman penelitian.", "standard_criteria_id" => "13" ],
    [ "id" => "109", "name" => "Lembaga penelitian membentuk kelompok riset sesuai dengan renstra penelitian", "standard_criteria_id" => "13" ],
    [ "id" => "110", "name" => "Lembaga penelitian memastikan dosen peneliti direkognisi oleh pihak eksternal atas kepakarannya", "standard_criteria_id" => "13" ],
    [ "id" => "111", "name" => "Lembaga penelitian memastikan penelitian yang dikelolanya turut melibatkan peneliti asing", "standard_criteria_id" => "13" ],
    [ "id" => "112", "name" => "Universitas memastikan ketersediaan sarana dan prasarana penelitian yang digunakan untuk memfasilitasi penelitian paling sedikit terkait dengan bidang ilmu program studi", "standard_criteria_id" => "14" ],
    [ "id" => "113", "name" => "Universitas memastikan sarana dan prasarana penelitian sudah memenuhi standar mutu, keselamatan kerja, kesehatan, kenyamanan, dan keamanan peneliti, masyarakat, dan lingkungan.", "standard_criteria_id" => "14" ],
    [ "id" => "114", "name" => "Universitas memiliki laboratorium riset yang dapat menghasilkan produk riset yang bermanfaat untuk masyarakat dan berdaya saing", "standard_criteria_id" => "14" ],
    [ "id" => "115", "name" => "Universitas memastikan pelaksana standar pengelolaan penelitian dilakukan oleh Lembaga Penelitian", "standard_criteria_id" => "15" ],
    [ "id" => "116", "name" => "Lembaga penelitian wajib menyusun dan mengembangkan rencana program penelitian sesuai dengan rencana strategis penelitian", "standard_criteria_id" => "15" ],
    [ "id" => "117", "name" => "Lembaga penelitian wajib menyusun dan mengembangkan peraturan, panduan, dan sistem penjaminan mutu internal kegiatan penelitian", "standard_criteria_id" => "15" ],
    [ "id" => "118", "name" => "Lembaga penelitian wajib memfasilitasi pelaksanaan kegiatan penelitian", "standard_criteria_id" => "15" ],
    [ "id" => "119", "name" => "Lembaga penelitian wajib melaksanakan pemantauan dan evaluasi pelaksanaan penelitian", "standard_criteria_id" => "15" ],
    [ "id" => "120", "name" => "Lembaga penelitian wajib melakukan diseminasi hasil penelitian", "standard_criteria_id" => "15" ],
    [ "id" => "121", "name" => "Lembaga penelitian wajib memfasilitasi peningkatan kemampuan peneliti untuk melaksanakan penelitian, penulisan artikel ilmiah, dan perolehan kekayaan intelektual (KI)", "standard_criteria_id" => "15" ],
    [ "id" => "122", "name" => "Lembaga penelitian wajib memberikan penghargaan kepada peneliti yang berprestasi", "standard_criteria_id" => "15" ],
    [ "id" => "123", "name" => "Lembaga penelitian wajib melaporkan kegiatan penelitian yang dikelolanya setiap tahun kepada Rektor", "standard_criteria_id" => "15" ],
    [ "id" => "124", "name" => "Universitas memiliki rencana strategis penelitian yang merupakan bagian dari rencana strategis perguruan tinggi", "standard_criteria_id" => "15" ],
    [ "id" => "125", "name" => "Universitas wajib menyusun kriteria dan prosedur penilaian penelitian paling sedikit menyangkut aspek peningkatan jumlah publikasi ilmiah, penemuan baru di bidang ilmu pengetahuan dan teknologi, dan jumlah dan mutu bahan ajar;", "standard_criteria_id" => "15" ],
    [ "id" => "126", "name" => "Universitas wajib melakukan pemantauan dan evaluasi terhadap lembaga atau fungsi penelitian dalam melaksanakan program penelitian", "standard_criteria_id" => "15" ],
    [ "id" => "127", "name" => "Universitas wajib menjaga dan meningkatkan mutu pengelolaan lembaga atau fungsi penelitian dalam menjalankan program penelitian secara berkelanjutan", "standard_criteria_id" => "15" ],
    [ "id" => "128", "name" => "Universitas wajib memiliki panduan tentang kriteria peneliti dengan mengacu pada standar hasil, standar isi, dan standar proses penelitian", "standard_criteria_id" => "15" ],
    [ "id" => "129", "name" => "Universitas wajib mendayagunakan sarana dan prasarana pada lembaga lain melalui kerja sama penelitian", "standard_criteria_id" => "15" ],
    [ "id" => "130", "name" => "Universitas wajib melakukan analisis kebutuhan yang menyangkut jumlah, jenis, dan spesifikasi sarana dan prasarana penelitian", "standard_criteria_id" => "15" ],
    [ "id" => "131", "name" => "Universitas wajib menyampaikan laporan kinerja lembaga atau fungsi penelitian dalam menyelenggarakan program penelitian paling sedikit melalui pangkalan data pendidikan tinggi","standard_criteria_id" => "15"],
    [ "id" => "132", "name" => "Universitas wajib melakukan kerjasama (termasuk di dalamnya kerjasama bidang penelitian) dengan lembaga lain baik di tingkat nasional maupun internasional", "standard_criteria_id" => "15"],
    [ "id" => "133", "name" => "Lembaga penelitian wajib melaksanakan survei untuk mengukur tingkat kepuasan pemangku kepentingan internal dan eksternal terhadap pengelolaan penelitian", "standard_criteria_id" => "15"],
    [ "id" => "134", "name" => "Universitas wajib mengimplementasikan integrasi penelitian dalam pembelajaran", "standard_criteria_id" => "15"],
    [ "id" => "135", "name" => "Lembaga penelitian harus melakukan update isi web dengan info-info terkini bidang penelitian", "standard_criteria_id" => "15"],
    [ "id" => "136", "name" => "Universitas wajib menyediakan dana internal untuk penelitian", "standard_criteria_id" => "16"],
    [ "id" => "137", "name" => "Universitas/LPPM/Program Studi mengupayakan pendanaan penelitian dapat bersumber dari pemerintah, kerja sama dengan lembaga lain di dalam maupun di luar negeri, atau dana dari masyarakat.", "standard_criteria_id" => "16"],
    [ "id" => "138", "name" => "Universitas memiliki kebijakan yang mengatur mekanisme pendanaan dan pembiayaan penelitian", "standard_criteria_id" => "16"],
    [ "id" => "139", "name" => "Universitas wajib menyediakan dana pengelolaan penelitian", "standard_criteria_id" => "16"],
    [ "id" => "140", "name" => "Universitas wajib membiayai kegiatan hilirisasi hasil penelitian", "standard_criteria_id" => "16"],
    [ "id" => "141", "name" => "Lembaga Kemahasiswaan dan Pengabdian Masyarakat mendorong hasil PkM berupa penyelesaian masalah yang dihadapi masyarakat dengan memanfaatkan keahlian civitas academica yang relevan", "standard_criteria_id" => "17"],
    [ "id" => "142", "name" => "Lembaga Kemahasiswaan dan Pengabdian Masyarakat mendorong hasil PkM berupa pemanfaatan teknologi tepat guna", "standard_criteria_id" => "17"],
    [ "id" => "143", "name" => "Lembaga Kemahasiswaan dan Pengabdian Masyarakat mendorong hasil PkM berupa bahan pengembangan ilmu pengetahuan dan teknologi", "standard_criteria_id" => "17"],
    [ "id" => "144", "name" => "Lembaga Kemahasiswaan dan Pengabdian Masyarakat mendorong hasil PkM menjadi bahan ajar atau modul pelatihan untuk pengayaan sumber belajar", "standard_criteria_id" => "17"],
    [ "id" => "145", "name" => "Lembaga Kemahasiswaan dan Pengabdian Masyarakat mewajibkan semua hasil PkM dosen dipublikasikan di tingkat nasional dan Internasional", "standard_criteria_id" => "17"],
    [ "id" => "146", "name" => "Lembaga Kemahasiswaan dan Pengabdian Masyarakat mendorong PkM dosen menghasilkan Mitra Berbadan Hukum", "standard_criteria_id" => "17"],
    [ "id" => "147", "name" => "Lembaga Kemahasiswaan dan Pengabdian Masyarakat memastikan kedalaman dan keluasan materi PkM bersumber dari hasil penelitian atau pengembangan ilmu pengetahuan dan teknologi yang dapat diterapkan langsung dan dibutuhkan oleh masyarakat pengguna", "standard_criteria_id" => "18"],
    [ "id" => "148", "name" => "Lembaga Kemahasiswaan dan Pengabdian Masyarakat memiliki dokumen formal Rencana Strategis Pengabdian kepada Masyarakat yang memuat landasan pengembangan, peta jalan penelitian, sumber daya, sasaran program strategis dan indikator kinerja", "standard_criteria_id" => "19"],
    [ "id" => "149", "name" => "Lembaga Kemahasiswaan dan Pengabdian Masyarakat memiliki pedoman pengabdian kepada masyarakat yang mencakup perencanaan, pelaksanaan, dan pelaporan kegiatan", "standard_criteria_id" => "19"],
    [ "id" => "150", "name" => "Program studi memiliki peta jalan PkM yang mengacu pada peta jalan PkM di dalam Renstra PkM Universitas", "standard_criteria_id" => "19"],
    [ "id" => "151", "name" => "Dosen yang akan melakukan kegiatan PkM harus mengajukan proposal sesuai dengan pedoman yang telah ditetapkan melalui Sistem Informasi Penelitian dan Pengabdian Kepada Masyarakat", "standard_criteria_id" => "19"],
    [ "id" => "152", "name" => "Lembaga Kemahasiswaan dan Pengabdian Masyarakat menunjuk reviewer untuk melakukan proses penilaian terhadap pengajuan PkM dosen", "standard_criteria_id" => "19"],
    [ "id" => "153", "name" => "LPPM mengumumkan usulan PkM yang diterima", "standard_criteria_id" => "19"],
    [ "id" => "154", "name" => "Dosen harus melaksanaan PkM sesuai pedoman penelitian yang ditetapkan", "standard_criteria_id" => "19"],
    [ "id" => "155", "name" => "Lembaga Kemahasiswaan dan Pengabdian Masyarakat memastikan kegiatan pengabdian kepada masyarakat wajib mempertimbangkan standar mutu, keselamatan kerja, kesehatan, kenyamanan, serta keamanan pelaksana, masyarakat, dan lingkungan", "standard_criteria_id" => "19"],
    [ "id" => "156", "name" => "Program Studi memastikan kegiatan pengabdian kepada masyarakat yang dilakukan oleh mahasiswa sebagai salah satu dari bentuk pembelajaran harus diarahkan untuk memenuhi capaian pembelajaran lulusan dan ketentuan", "standard_criteria_id" => "19"],
    [ "id" => "157", "name" => "Program Studi memastikan kegiatan pengabdian kepada masyarakat yang dilakukan oleh mahasiswa dinyatakan dalam besaran sks", "standard_criteria_id" => "19"],
    [ "id" => "158", "name" => "Lembaga Kemahasiswaan dan Pengabdian Masyarakat memastikan kegiatan PkM harus diselenggarakan secara terarah, terukur, dan terprogram", "standard_criteria_id" => "19"],
    [ "id" => "159", "name" => "Dosen wajib membuat laporan kemajuan PkM yang berisi pencapaian PkM sementara sesuai dengan pedoman yang telah ditetapkan melalui Sistem.............", "standard_criteria_id" => "19"],
    [ "id" => "160", "name" => "Lembaga Kemahasiswaan dan Pengabdian Masyarakat harus melakukan pemantauan kegiatan PkM melalui laporan kemajuan PkM yang dilakukan oleh dosen", "standard_criteria_id" => "19"],
    [ "id" => "161", "name" => "Dosen dan/atau mahasiswa wajib membuat laporan akhir PkM yang berisi capaian akhir PkM sesuai dengan pedoman yang telah ditetapkan melalui Sistem.............","standard_criteria_id" => "19"],
    [ "id" => "162", "name" => "Lembaga Kemahasiswaan dan Pengabdian Masyarakat harus melakukan penilaian atas pencapaian kegiatan PkM yang dilakukan dosen","standard_criteria_id" => "19"],
    [ "id" => "163", "name" => "Lembaga Kemahasiswaan dan Pengabdian Masyarakat memastikan penilaian proses dan hasil PkM dilakukan secara terintegrasi dan memenuhi unsur edukatif, objektif, akuntabel, dan transparan","standard_criteria_id" => "20"],
    [ "id" => "164", "name" => "Lembaga Kemahasiswaan dan Pengabdian Masyarakat memastikan penilaian proses dan hasil PkM memperhatikan kesesuaian dengan strandar hasil, standar isi, dan standar proses PkM","standard_criteria_id" => "20"],
    [ "id" => "165", "name" => "Lembaga Kemahasiswaan dan Pengabdian Masyarakat memastikan penilaian proses dan hasil pengabdian kepada masyarakat telah memenuhi standar minimal","standard_criteria_id" => "20"],
    [ "id" => "166", "name" => "Pelaksana PkM harus melakukan penilaian hasil dan proses PkM menggunakan metode dan instrumen yang relevan, akuntabel, dan dapat mewakili ukuran ketercapaian kinerja proses serta pencapaian kinerja hasil pengabdian kepada masyarakat.","standard_criteria_id" => "20"],
    [ "id" => "167", "name" => "Ketua Lembaga Kemahasiswaan dan Pengabdian Masyarakat memastikan bahwa pelaksana PkM memiliki kemampuan untuk melaksanakan pengabdian kepada masyarakat","standard_criteria_id" => "21"],
    [ "id" => "168", "name" => "Pelaksana PkM wajib memiliki penguasaan metodologi penerapan keilmuan yang sesuai dengan bidang keahlian, jenis kegiatan, serta tingkat kerumitan dan kedalaman sasaran kegiatan","standard_criteria_id" => "21"],
    [ "id" => "169", "name" => "Lembaga Kemahasiswaan dan Pengabdian Masyarakat membentuk kelompok pelaksana pengabdian sesuai dengan renstra PkM","standard_criteria_id" => "21"],
    [ "id" => "170", "name" => "Pelaksana PkM wajib melibatkan mahasiswa dalam kegiatan PkM","standard_criteria_id" => "21"],
    [ "id" => "171", "name" => "Universitas harus memastikan ketersediaan sarana dan prasarana PkM sesuai standar isi dan proses PkM","standard_criteria_id" => "22"],
    [ "id" => "172", "name" => "Universitas harus memastikan sarana dan prasarana PkM harus memenuhi standar mutu, keselamatan kerja, kesehatan, kenyamanan, dan keamanan","standard_criteria_id" => "22"],
    [ "id" => "173", "name" => "Universitas memastikan pelaksana standar pengelolaan pengabdian kepada masyarakat dilakukan oleh Lembaga Kemahasiswaan dan Pengabdian Masyarakat sebagai Unit Pengelola PkM.","standard_criteria_id" => "23"],
    [ "id" => "174", "name" => "Lembaga Kemahasiswaan dan Pengabdian Masyarakat wajib menyusun dan mengembangkan rencana program pengabdian kepada masyarakat sesuai dengan rencana strategis pengabdian kepada masyarakat perguruan tinggi","standard_criteria_id" => "23"],
    [ "id" => "175", "name" => "Lembaga Kemahasiswaan dan Pengabdian Masyarakat wajib menyusun dan mengembangkan peraturan, panduan, dan sistem penjaminan mutu internal kegiatan pengabdian kepada masyarakat","standard_criteria_id" => "23"],
    [ "id" => "176", "name" => "Lembaga Kemahasiswaan dan Pengabdian Masyarakat wajib memfasilitasi pelaksanaan kegiatan pengabdian kepada masyarakat","standard_criteria_id" => "23"],
    [ "id" => "177", "name" => "Lembaga Kemahasiswaan dan Pengabdian Masyarakat wajib melaksanakan pemantauan dan evaluasi pelaksanaan pengabdian kepada masyarakat","standard_criteria_id" => "23"],
    [ "id" => "178", "name" => "Lembaga Kemahasiswaan dan Pengabdian Masyarakat wajib melakukan diseminasi hasil pengabdian kepada masyarakat","standard_criteria_id" => "23"],
    [ "id" => "179", "name" => "Lembaga Kemahasiswaan dan Pengabdian Masyarakat wajib memfasilitasi kegiatan peningkatan kemampuan pelaksana pengabdian kepada masyarakat","standard_criteria_id" => "23"],
    [ "id" => "180", "name" => "Lembaga Kemahasiswaan dan Pengabdian Masyarakat wajib memberikan penghargaan kepada pelaksana pengabdian kepada masyarakat yang berprestasi","standard_criteria_id" => "23" ],
    [ "id" => "181", "name" => "Lembaga Kemahasiswaan dan Pengabdian Masyarakat wajib mendayagunakan sarana dan prasarana pengabdian kepada masyarakat pada lembaga lain melalui kerja sama","standard_criteria_id" => "23"],
    [ "id" => "182", "name" => "Lembaga Kemahasiswaan dan Pengabdian Masyarakat wajib melakukan analisis kebutuhan yang menyangkut jumlah, jenis, dan spesifikasi sarana dan prasarana pengabdian kepada masyarakat", "standard_criteria_id" => "23"],
    [ "id" => "183", "name" => "Lembaga Kemahasiswaan dan Pengabdian Masyarakat wajib menyusun laporan kegiatan pengabdian pada masyarakat yang dikelolanya kepada Rektor", "standard_criteria_id" => "23"],
    [ "id" => "184", "name" => "Universitas wajib memiliki rencana strategis pengabdian kepada masyarakat yang merupakan bagian dari rencana strategis perguruan tinggi", "standard_criteria_id" => "23"],
    [ "id" => "185", "name" => "Universitas wajib menyusun kriteria dan prosedur penilaian pengabdian kepada masyarakat paling sedikit menyangkut aspek hasil pengabdian kepada masyarakat dalam menerapkan, mengamalkan, dan membudayakan ilmu pengetahuan dan teknologi guna memajukan kesejahteraan umum serta mencerdaskan kehidupan bangsa", "standard_criteria_id" => "23"],
    [ "id" => "186", "name" => "Universitas wajib menjaga dan meningkatkan mutu pengelolaan lembaga atau fungsi pengabdian kepada masyarakat dalam menjalankan program pengabdian kepada masyarakat secara berkelanjutan", "standard_criteria_id" => "23"],
    [ "id" => "187", "name" => "Universitas wajib melakukan pemantauan dan evaluasi terhadap lembaga atau fungsi pengabdian kepada masyarakat dalam melaksanakan program pengabdian kepada masyarakat", "standard_criteria_id" => "23"],
    [ "id" => "188", "name" => "Universitas wajib memiliki panduan tentang kriteria pelaksana pengabdian kepada masyarakat dengan mengacu pada standar hasil, standar isi, dan standar proses pengabdian kepada masyarakat", "standard_criteria_id" => "23"],
    [ "id" => "189", "name" => "Universitas wajib mendayagunakan sarana dan prasarana pada lembaga lain melalui kerja sama pengabdian kepada masyarakat", "standard_criteria_id" => "23"],
    [ "id" => "190", "name" => "Universitas wajib melakukan analisis kebutuhan yang menyangkut jumlah, jenis, dan spesifikasi sarana dan prasarana pengabdian kepada masyarakat", "standard_criteria_id" => "23"],
    [ "id" => "191", "name" => "Universitas wajib menyampaikan laporan kinerja lembaga atau fungsi pengabdian kepada masyarakat dalam menyelenggarakan program pengabdian kepada masyarakat paling sedikit melalui pangkalan data pendidikan tinggi", "standard_criteria_id" => "23"],
    [ "id" => "192", "name" => "Universitas wajib mengimplementasikan integrasi penelitian dan PkM dalam pembelajaran", "standard_criteria_id" => "23"],
    [ "id" => "193", "name" => "Lembaga Kemahasiswaan dan Pengabdian Masyarakat harus melakukan update isi web dengan info-info terkini bidang penelitian dan PkM", "standard_criteria_id" => "23"],
    [ "id" => "194", "name" => "Universitas wajib menyediakan dana internal untuk pengabdian kepada masyarakat", "standard_criteria_id" => "24"],
    [ "id" => "195", "name" => "Universitas/Lembaga Kemahasiswaan dan Pengabdian Masyarakat/Prodi mengupayakan pendanaan pengabdian kepada masyarakat selain pendanaan dari internal universitas.", "standard_criteria_id" => "24"],
    [ "id" => "196", "name" => "Universitas memiliki pedoman yang mengatur mekanisme pendanaan dan pembiayaan pengabdian kepada masyarakat", "standard_criteria_id" => "24"],
    [ "id" => "197", "name" => "Universitas wajib menyediakan dana pengelolaan pengabdian kepada masyarakat", "standard_criteria_id" => "24"],
    [ "id" => "198", "name" => "Yayasan JGU memiliki kebijakan dasar pendirian Yayasan JGU", "standard_criteria_id" => "25"],
    [ "id" => "199", "name" => "Yayasan JGU harus memiliki kebijakan struktur organisasi JGU", "standard_criteria_id" => "25"],
    [ "id" => "200", "name" => "JGU memiliki Kebijakan yang mengatur tentang Senat", "standard_criteria_id" => "25"],
    [ "id" => "201", "name" => "JGU memiliki kebijakan yang mengatur Dewan Penyantun JGU", "standard_criteria_id" => "25"],
    [ "id" => "202", "name" => "Universitas/Fakultas/Pascasarjana mengelola lembaga berbasis manajemen resiko", "standard_criteria_id" => "26"],
    [ "id" => "203", "name" => "Universitas/Fakultas/Pascasarjana menjamin pengelolaan lembaga dilakukan berbasis Good University Governance", "standard_criteria_id" => "26"],
    [ "id" => "204", "name" => "Universitas harus memiliki kebijakan penerimaan mahasiswa baru berdasarkan kesempatan yang sama", "standard_criteria_id" => "27"],
    [ "id" => "205", "name" => "Universitas memiliki kebijakan penerimaan mahasiswa asing", "standard_criteria_id" => "27"],
    [ "id" => "206", "name" => "Universitas memiliki pedoman Penerimaan Mahasiswa Baru agar pelaksanaan penerimaan mahasiswa baru berjalan efektif dan efisien", "standard_criteria_id" => "27"],
    [ "id" => "207", "name" => "Universitas memiliki sistem penerimaan mahasiswa baru secara online", "standard_criteria_id" => "27"],
    [ "id" => "208", "name" => "Universitas menentukan jadwal, jalur dan metode seleksi", "standard_criteria_id" => "27"],
    [ "id" => "209", "name" => "Universitas menentukan jadwal, jalur dan metode seleksi", "standard_criteria_id" => "27"],
    [ "id" => "210", "name" => "Universitas menentukan jadwal, jalur dan metode seleksi", "standard_criteria_id" => "27"],
    [ "id" => "211", "name" => "Universitas mensosialisasikan informasi penerimaan mahasiswa baru kepada masyarakat melalui media online", "standard_criteria_id" => "27"],
    [ "id" => "212", "name" => "Fakultas/Pascasarjana menetapkan jumlah daya tampung masing-masing program studi dengan mengacu pada rasio dosen dan mahasiswa serta mempertimbangkan ketersediaan sarana dan prasarana yang ada", "standard_criteria_id" => "27"],
    [ "id" => "213", "name" => "Universitas mengumumkan hasil seleksi penerimaan mahasiswa baru secara online", "standard_criteria_id" => "27"],
    [ "id" => "214", "name" => "Universitas/Fakultas/Pascasarjana melakukan evaluasi terhadap efektifitas penerimaan mahasiswa baru", "standard_criteria_id" => "27"],
    [ "id" => "215", "name" => "Fakultas/Pascasarjana/Program studi melakukan upaya untuk meningkatkan animo calon", "standard_criteria_id" => "27"],
    [ "id" => "216", "name" => "Universitas memiliki regulasi yang mengatur pengelolaan kegiatan kemahasiswaan, sebagai komitmen perguruan tinggi dalam pengembangan kemahasiswaan.", "standard_criteria_id" => "28"],
    [ "id" => "217", "name" => "Universitas memiliki regulasi yang mengatur pengelolaan beasiswa bagi mahasiswa", "standard_criteria_id" => "28"],
    [ "id" => "218", "name" => "Universitas/Bagian Kemahasiswaan harus mengupayakan sumber-sumber beasiswa di luar beasiswa yang bersumber dari APBN (Beasiswa dapat bersumber dari APBD, BUMN maupun pihak swasta)", "standard_criteria_id" => "28"],
    [ "id" => "219", "name" => "Universitas menyediakan jaminan biaya kesehatan atau perawatan bagi mahasiswa yang sakit/santunan bagi yang meninggal dunia", "standard_criteria_id" => "28"],
    [ "id" => "220", "name" => "Universitas memiliki unit layanan konseling yang diperuntukkan untuk menyelesaikan permasalahan mahasiswa", "standard_criteria_id" => "28"],
    [ "id" => "221", "name" => "Universitas/Fakultas/Bagian Kemahasiswaan memiliki program pembinaan karakter yang merupakan program kegiatan terstruktur untuk mengembangkan kepribadian nasional yang berdasarkan nilai-nilai Pancasila", "standard_criteria_id" => "28"],
    [ "id" => "222", "name" => "Universitas/Fakultas/Bagian Kemahasiswaan memiliki program pendidikan karakter keagamaan", "standard_criteria_id" => "28"],
    [ "id" => "223", "name" => "Universitas/Bagian Kemahasiswaan memiliki program pembinaan kewirausahaan mahasiswa untuk menumbuhkembangkan jiwa kewirausahaan mahasiswa (entrepreneurship mindset)", "standard_criteria_id" => "28"],
    [ "id" => "224", "name" => "Universitas/Bagian Kemahasiswaan menyelenggarakan program pengembangan pusat karir", "standard_criteria_id" => "28"],
    [ "id" => "225", "name" => "Universitas/Bagian Kemahasiswaan melakukan kegiatan penelusuran alumni melalui tracer study terhadap lulusan TS-2", "standard_criteria_id" => "28"],
    [ "id" => "226", "name" => "Universitas/Bagian Kemahasiswaan melakukan survey kepuasan pengguna lulusan setiap tahun", "standard_criteria_id" => "28"],
    [ "id" => "227", "name" => "Universitas/Bagian Kemahasiswaan melakukan analisis terhadap hasil penelusuran alumni", "standard_criteria_id" => "28"],
    [ "id" => "228", "name" => "Universitas/Lembaga Kemahasiswaan harus menyediakan sarana prasarana kegiatan kemahasiswaan yang ditujukan untuk memfasilitasi kegiatan kemahasiswaan", "standard_criteria_id" => "29"],
    [ "id" => "229", "name" => "Universitas harus memiliki alokasi dana kemahasiswaan atau anggaran kemahasiswaan untuk pembinaan dan pengembangan kegiatan kemahasiswaan (tidak termasuk beasiswa)", "standard_criteria_id" => "30"],
    [ "id" => "230", "name" => "Universitas memiliki peraturan yang mengatur tentang pemberian penghargaan terhadap prestasi mahasiswa", "standard_criteria_id" => "31"],
    [ "id" => "231", "name" => "Bagian Kemahasiswaan/Fakultas/Program Studi memastikan terlaksananya program/kegiatan kewirausahaan mahasiswa", "standard_criteria_id" => "31"],
    [ "id" => "232", "name" => "Bagian Kemahasiswaan/Fakultas/Program Studi melakukan pengiriman mahasiswa dalam kegiatan intra/ko dan ekstrakurikuler keluar negeri atau menerima mahasiswa asing melakukan kegiatan intra/ko dan ekstrakurikuler", "standard_criteria_id" => "31"],
    [ "id" => "233", "name" => "Bagian Kemahasiswaan/Fakultas/Program Studi memastikan terlaksananya program pengabdian kepada masyarakat (tidak termasuk Kuliah Kerja Nyata (KKN), Program Kreativitas Mahasiswa, dan PHBD) yang dilakukan oleh kelompok/organisasi kemahasiswaan dan keikutsertaan mahasiswa dalam pengabdian dosen", "standard_criteria_id" => "31"],
    [ "id" => "234", "name" => "Lembaga Kemahasiswaan memastikan diperolehnya rekognisi mahasiswa pada sebuah kegiatan yang diselenggarakan oleh lembaga penyelenggara secara mandiri selain dari lembaga Direktorat Kemahasiswaan, Direktorat Jenderal Pembelajaran dan Kemahasiswaan", "standard_criteria_id" => "31"],
    [ "id" => "235", "name" => "Bagian Kemahasiswaan/Fakultas/Program Studi memastikan diperolehnya prestasi mahasiswa pada ko dan ekstrakurikuler mandiri", "standard_criteria_id" => "31"],
    [ "id" => "236", "name" => "Bagian Kemahasiswaan memastikan diperolehnya prestasi mahasiswa pada ko dan ekstrakurikuler BELMAWA", "standard_criteria_id" => "31"],
    [ "id" => "237", "name" => "Bagian Kemahasiswaan/Fakultas/Program Studi memastikan diperolehnya prestasi mahasiswa dalam bidang akademik dan non akademik", "standard_criteria_id" => "31"],
    [ "id" => "238", "name" => "Universitas memiliki kelembagaan yang mengatur dan pengelolaan bagian kerja sama, sebagai komitmen perguruan tinggi dalam pengembangan jejaring dalam dan luar negeri", "standard_criteria_id" => "32"],
    [ "id" => "239", "name" => "Universitas memiliki pedoman yang mengatur mengenai sistem dan prosedur pengelolaan kelembagaan kerja sama", "standard_criteria_id" => "32"],
    [ "id" => "240", "name" => "Fakultas/Pascasarjana memiliki kelembagaan setingkat kasie untuk pengelolaan kerja sama", "standard_criteria_id" => "32"],
    [ "id" => "241", "name" => "JGU menyediakan Sistem Operasional Prosedur untuk pelaksanaan kegiatan yang dijembatani dengan kerja sama dalam negeri", "standard_criteria_id" => "33"],
    [ "id" => "242", "name" => "JGU menyediakan Sistem Operasional Prosedur untuk Pelaksanaan Kegiatan yang dijembatani dengan Kerja Sama Luar Negeri", "standard_criteria_id" => "33"],
    [ "id" => "243", "name" => "Universitas Islam Bandung memiliki pedoman yang mengatur tupoksi dan job description dalam tata pamong dan tata kelola akademik", "standard_criteria_id" => "34"],
    [ "id" => "244", "name" => "Universitas Islam Bandung memiliki SOP yang mengatur tentang tata pamong dan tata kelola di tingkat universitas, fakultas, pascasarjana, lembaga dan unit", "standard_criteria_id" => "34"],
    [ "id" => "245", "name" => "Fakultas menjamin ketersediaan Formulir Rencana Studi sebelum pelaksanaan perwalian", "standard_criteria_id" => "35"],
    [ "id" => "246", "name" => "Mahasiswa harus melakukan pengisian FRS/perwalian sesuai jadwal yang telah ditentukan", "standard_criteria_id" => "35"],
    [ "id" => "247", "name" => "Dosen wali memberikan pelayanan kepada mahasiswa dalam proses perwalian", "standard_criteria_id" => "35"],
    [ "id" => "248", "name" => "Fakultas menjamin ketersediaan Buku Panduan Akademik serta mendistribusikannya kepada mahasiswa baru pada saat ta’aruf", "standard_criteria_id" => "35"],
    [ "id" => "249", "name" => "Fakultas menyusun Jadwal Kuliah sebelum perkuliahan dimulai", "standard_criteria_id" => "35"],
    [ "id" => "250", "name" => "Fakultas menyusun Jadwal Praktikum sebelum kegiatan praktikum dimulai", "standard_criteria_id" => "35"],
    [ "id" => "251", "name" => "Fakultas/Bagian Akademik menjamin ketersediaan Daftar Hadir Mahasiswa dan Dosen (DHMD) sebelum perkuliahan dimulai", "standard_criteria_id" => "35"],
    [ "id" => "252", "name" => "Fakultas/Bagian Akademik harus menyediakan Berita Acara Perkuliahan (BAP) sebelum perkuliahan dimulai", "standard_criteria_id" => "35"],
    [ "id" => "253", "name" => "Fakultas/Bagian Akademik harus menyiapkan jadwal ujian sebelum pelaksanaan ujian", "standard_criteria_id" => "36"],
    [ "id" => "254", "name" => "Fakultas/Bagian Akademik harus menyusun jadwal pengawas ujian pelaksanaan ujian", "standard_criteria_id" => "36"],
    [ "id" => "255", "name" => "Dosen harus menyerahkan Soal Ujian sebelum pelaksanaan ujian", "standard_criteria_id" => "36"],
    [ "id" => "256", "name" => "Soal ujian harus diverifikasi oleh tim sebelum digandakan", "standard_criteria_id" => "36"],
    [ "id" => "257", "name" => "Panitia ujian mengirimkan lembar jawaban kepada dosen setelah pelaksanaan ujian", "standard_criteria_id" => "36"]

                ];

        foreach ($data as $x) {
            if(!StandardStatement::where('id', $x['id'])->first()){
                $m = new StandardStatement();
                $m->id = $x['id'];
                $m->name = $x['name'];
                $m->standard_criteria_id = $x['standard_criteria_id'];
                $m->save();
            }
        }
    }
}
